server: 
  port: 8085
  
spring:
  application:
    name: zuul
    
zuul:
  routes:
    starter:
      path: /starter/**
      serviceId: starter
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/